# Generated by Django 3.1.4 on 2021-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_shop', '0004_auto_20210111_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_arrivals',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
