# Generated by Django 3.1.4 on 2021-01-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_shop', '0005_new_arrivals_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='pdf',
            field=models.FileField(default=True, upload_to='ebook_shop/files'),
        ),
    ]
