# Generated by Django 3.1.4 on 2021-01-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_shop', '0006_auto_20210125_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='id',
            new_name='book_id',
        ),
    ]
