# Generated by Django 3.1.4 on 2021-01-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_shop', '0007_auto_20210125_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.RenameField(
            model_name='new_arrivals',
            old_name='book_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='new_arrivals',
            name='pdf',
            field=models.FileField(upload_to='ebook_shop/files'),
        ),
    ]
